# Generated by Django 4.2.28 on 2026-05-25 08:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft (vendor working)'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('awarded', 'Awarded'), ('withdrawn', 'Withdrawn')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('delivery_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rank', '-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('rfq', 'Request for Quotation (RFQ)'), ('rfp', 'Request for Proposal (RFP)'), ('rft', 'Request for Tender (RFT)'), ('tender', 'Open Tender')], default='rfq', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open for bids'), ('closed', 'Closed (bidding ended)'), ('under_evaluation', 'Under evaluation'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('award_target_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('allow_partial_award', models.BooleanField(default=False)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('award_notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_events', to='vendors.vendor')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_events_cancelled', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_events', to='vendors.vendorcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_events_created', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, help_text='Source requisition this event was spawned from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_events', to='requisitions.requisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingEventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('item_description', models.CharField(max_length=255)),
                ('uom', models.CharField(default='EA', help_text='Unit of measure', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('est_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('required_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_items', to='requisitions.accountcode')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sourcing.sourcingevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'unique_together': {('event', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='SourcingCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('criterion_type', models.CharField(choices=[('price', 'Price'), ('quality', 'Quality'), ('delivery', 'Delivery'), ('compliance', 'Compliance'), ('experience', 'Experience'), ('other', 'Other')], default='other', max_length=15)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight in percent (0–100). All weights on an event should sum to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='sourcing.sourcingevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SourcingAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('approved', 'Approved'), ('contracted', 'Contracted'), ('cancelled', 'Cancelled')], default='recommended', max_length=12)),
                ('justification', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_awards_made', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='sourcing.bid')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='sourcing.sourcingevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_awards', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='BidLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_offered', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sourcing.bid')),
                ('event_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_lines', to='sourcing.sourcingeventitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['event_item__line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BidEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('comment', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sourcing.bid')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sourcing.sourcingcriterion')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_evaluations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='bid_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sourcing.bid')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sourcing.sourcingevent'),
        ),
        migrations.AddField(
            model_name='bid',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='bid',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='SourcingEventInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('viewed', 'Viewed'), ('submitted', 'Submitted bid'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='invited', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='sourcing.sourcingevent')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_invitations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['tenant', 'vendor', 'status'], name='sourcing_so_tenant__168de0_idx')],
                'unique_together': {('event', 'vendor')},
            },
        ),
        migrations.AddIndex(
            model_name='sourcingevent',
            index=models.Index(fields=['tenant', 'status'], name='sourcing_so_tenant__0bb302_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcingevent',
            index=models.Index(fields=['tenant', 'event_type'], name='sourcing_so_tenant__433620_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcingevent',
            unique_together={('tenant', 'event_number')},
        ),
        migrations.AddIndex(
            model_name='sourcingaward',
            index=models.Index(fields=['tenant', 'event', 'status'], name='sourcing_so_tenant__865337_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bidline',
            unique_together={('bid', 'event_item')},
        ),
        migrations.AddIndex(
            model_name='bidevaluation',
            index=models.Index(fields=['tenant', 'bid'], name='sourcing_bi_tenant__4d9e29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bidevaluation',
            unique_together={('bid', 'criterion', 'evaluator')},
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tenant', 'status'], name='sourcing_bi_tenant__d27475_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['event', 'rank'], name='sourcing_bi_event_i_e4757f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('event', 'vendor')},
        ),
    ]
