# Generated by Django 4.2.28 on 2026-05-30 14:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sourcing', '0001_initial'),
        ('requisitions', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('msa', 'Master Service Agreement'), ('sow', 'Statement of Work'), ('nda', 'Non-Disclosure Agreement'), ('service', 'Service Agreement'), ('supply', 'Supply Agreement'), ('lease', 'Lease'), ('framework', 'Framework Agreement'), ('purchase', 'Purchase Agreement'), ('other', 'Other')], default='other', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('body', models.TextField(blank=True, help_text='Authored contract text, assembled from clauses.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_term_months', models.PositiveIntegerField(default=12, help_text='Length of an auto-renewal / renewal term.')),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, help_text='Raise an alert this many days before end_date.')),
                ('renewal_alerted_at', models.DateTimeField(blank=True, help_text='Set when the renewal alert was raised (idempotency guard).', null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('signature_sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='vendors.vendorcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Internal contract manager / owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_owned', to=settings.AUTH_USER_MODEL)),
                ('parent_contract', models.ForeignKey(blank=True, help_text='The predecessor contract this one was renewed from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.contract')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='requisitions.requisition')),
                ('sourcing_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sourcing.sourcingevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('payment', 'Payment Terms'), ('liability', 'Liability & Indemnity'), ('confidentiality', 'Confidentiality'), ('termination', 'Termination'), ('ip', 'Intellectual Property'), ('compliance', 'Compliance'), ('sla', 'Service Levels'), ('warranty', 'Warranty'), ('general', 'General')], default='general', max_length=20)),
                ('body', models.TextField(help_text='Standard clause text. May contain {{vendor_name}} tokens.')),
                ('is_standard', models.BooleanField(default=True, help_text='Standard, pre-approved by legal.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('msa', 'Master Service Agreement'), ('sow', 'Statement of Work'), ('nda', 'Non-Disclosure Agreement'), ('service', 'Service Agreement'), ('supply', 'Supply Agreement'), ('lease', 'Lease'), ('framework', 'Framework Agreement'), ('purchase', 'Purchase Agreement'), ('other', 'Other')], default='other', max_length=12)),
                ('is_shared', models.BooleanField(default=True, help_text='Visible to every user in the tenant.')),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('tenant', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ContractTemplateClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('clause', models.ForeignKey(blank=True, help_text='Library clause this slot was snapshotted from (provenance).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_uses', to='contracts.contractclause')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contracttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_status_events', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='contract_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amendment_number', models.CharField(max_length=48)),
                ('change_type', models.CharField(choices=[('value', 'Value change'), ('term_extension', 'Term extension'), ('scope', 'Scope change'), ('renewal', 'Renewal'), ('other', 'Other')], default='other', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('new_body', models.TextField(blank=True)),
                ('prev_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prev_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_amendments_applied', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_amendments_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='contract',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_terminated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(help_text='The supplier counterparty.', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='ContractSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.CharField(choices=[('internal', 'Internal stakeholder'), ('vendor', 'Supplier')], max_length=10)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('sign_token', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('signed_name', models.CharField(blank=True, help_text='Typed-name signature.', max_length=160)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_ip', models.CharField(blank=True, max_length=45)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Internal signer (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Supplier signer (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatures', to='vendors.vendor')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='contracts_c_tenant__ef2df9_idx')],
                'unique_together': {('contract', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ContractObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligation_type', models.CharField(choices=[('deliverable', 'Deliverable'), ('milestone', 'Milestone'), ('payment', 'Payment milestone'), ('penalty', 'Penalty / SLA credit'), ('sla', 'Service level'), ('report', 'Report / compliance')], default='deliverable', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment-milestone value (if applicable).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty / SLA credit on breach (if applicable).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('responsible_party', models.CharField(choices=[('internal', 'Internal stakeholder'), ('vendor', 'Supplier')], default='vendor', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_obligations', to='requisitions.accountcode')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_obligations_completed', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='contracts.contract')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_obligations_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='contracts_c_tenant__da1bdb_idx'), models.Index(fields=['tenant', 'due_date'], name='contracts_c_tenant__77e579_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractClauseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_uses', to='contracts.contractclause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_lines', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('contract', 'sort_order')},
            },
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['tenant', 'category'], name='contracts_c_tenant__38a597_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractclause',
            unique_together={('tenant', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='contractamendment',
            unique_together={('contract', 'amendment_number')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'status'], name='contracts_c_tenant__8ef07c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'contract_type'], name='contracts_c_tenant__ae36bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tenant', 'end_date'], name='contracts_c_tenant__2ba62c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('tenant', 'contract_number')},
        ),
    ]
