# Generated by Django 4.2.28 on 2026-05-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor',
            field=models.OneToOneField(blank=True, help_text='If set, this user is a vendor portal user sandboxed to /vendor-portal/.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user_link', to='vendors.vendor'),
        ),
    ]
