# Generated by Django 4.2.28 on 2026-05-29 06:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitions', '0001_initial'),
        ('sourcing', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction_number', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auction_type', models.CharField(choices=[('reverse', 'Reverse (lowest price wins)'), ('forward', 'Forward (highest price wins)')], default='reverse', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('starting_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ceiling — the first/maximum acceptable bid.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Hidden floor — buyer-only target below which the auction is a success.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('decrement_type', models.CharField(choices=[('amount', 'Fixed amount'), ('percent', 'Percent of current best')], default='amount', max_length=10)),
                ('decrement_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount (or percent) each new global-best bid must improve by.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('anti_snipe_seconds', models.PositiveIntegerField(default=120, help_text='A valid bid within this many seconds of end_at extends the auction.')),
                ('anti_snipe_extension_seconds', models.PositiveIntegerField(default=120, help_text='How far end_at is pushed out when anti-snipe fires.')),
                ('max_extensions', models.PositiveIntegerField(default=10, help_text='Cap on automatic anti-snipe extensions.')),
                ('extension_count', models.PositiveIntegerField(default=0)),
                ('rank_visibility', models.CharField(choices=[('rank_and_leading', 'Own rank + leading price (blind)'), ('rank_only', 'Own rank only'), ('full', 'Full leaderboard (open)')], default='rank_and_leading', max_length=20)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live (bidding open)'), ('closed', 'Closed (bidding ended)'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('award_notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_auctions', to='vendors.vendor')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_cancelled', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='vendors.vendorcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_created', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, help_text='Source requisition this auction was spawned from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='requisitions.requisition')),
                ('sourcing_event', models.ForeignKey(blank=True, help_text='Optional hand-off provenance from a sourcing event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='sourcing.sourcingevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='invited', max_length=12)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('current_bid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Latest (best) bid placed by this vendor.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_rank', models.PositiveIntegerField(blank=True, help_text='1 = lowest/leading.', null=True)),
                ('bid_count', models.PositiveIntegerField(default=0)),
                ('last_bid_at', models.DateTimeField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='auctions.auction')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_participations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['current_rank', '-current_bid_amount'],
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_no', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('uom', models.CharField(default='EA', help_text='Unit of measure', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('est_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_lots', to='requisitions.accountcode')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auctions.auction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['lot_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='auction_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='auctions.auction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('portal', 'Vendor portal'), ('manual', 'Buyer (on behalf)'), ('proxy', 'Proxy / auto-bid')], default='portal', max_length=10)),
                ('rank_at_placement', models.PositiveIntegerField(blank=True, null=True)),
                ('was_leading', models.BooleanField(default=False, help_text='Did this bid take the lead when placed?')),
                ('triggered_extension', models.BooleanField(default=False, help_text='Did this bid fire an anti-snipe extension?')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionparticipant')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bids_placed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auctionparticipant',
            index=models.Index(fields=['tenant', 'vendor', 'status'], name='auctions_au_tenant__87fe9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionparticipant',
            unique_together={('auction', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='auctionlot',
            unique_together={('auction', 'lot_no')},
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['auction', 'placed_at'], name='auctions_au_auction_09ee9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['auction', 'amount'], name='auctions_au_auction_3a2c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['tenant', 'status'], name='auctions_au_tenant__8a89f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['tenant', 'auction_type'], name='auctions_au_tenant__4590c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('tenant', 'auction_number')},
        ),
    ]
