# Generated by Django 4.2.28 on 2026-06-06 12:16

import hashlib
import json

from django.db import migrations, models


def _canonical(entry):
    return json.dumps(
        [
            entry.tenant_id, entry.user_id, entry.action, entry.level,
            entry.target_type, entry.target_id, entry.message, entry.payload,
            entry.created_at.isoformat() if entry.created_at else '',
        ],
        sort_keys=True, separators=(',', ':'), default=str,
    )


def _row_hash(prev_hash, entry):
    digest = hashlib.sha256()
    digest.update((prev_hash or '').encode('utf-8'))
    digest.update(b'|')
    digest.update(_canonical(entry).encode('utf-8'))
    return digest.hexdigest()


def backfill_hash_chain(apps, schema_editor):
    """Seed the tamper-evident chain for any audit rows that already exist, per tenant, in
    (created_at, id) order — the same order ``record_audit`` / ``verify_audit_chain`` use."""
    AuditLog = apps.get_model('tenants', 'AuditLog')
    tenant_ids = (AuditLog.objects.order_by().values_list('tenant_id', flat=True).distinct())
    for tenant_id in tenant_ids:
        prev_hash = ''
        rows = AuditLog.objects.filter(tenant_id=tenant_id).order_by('created_at', 'id')
        for entry in rows.iterator():
            entry.prev_hash = prev_hash
            entry.row_hash = _row_hash(prev_hash, entry)
            entry.save(update_fields=['prev_hash', 'row_hash'])
            prev_hash = entry.row_hash


def noop_reverse(apps, schema_editor):
    """Reverse just clears the chain fields (handled by RemoveField on full reverse)."""


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='row_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(backfill_hash_chain, noop_reverse),
    ]
