# Generated by Django 4.2.28 on 2026-05-25 15:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisitions', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rfx_type', models.CharField(choices=[('rfi', 'Request for Information (RFI)'), ('rfp', 'Request for Proposal (RFP)'), ('rfq', 'Request for Quotation (RFQ)')], default='rfi', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published (awaiting open date)'), ('open', 'Open for responses'), ('closed', 'Closed (responses ended)'), ('under_evaluation', 'Under evaluation'), ('completed', 'Completed (shortlisted)'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events_cancelled', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events', to='vendors.vendorcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events_created', to=settings.AUTH_USER_MODEL)),
                ('source_requisition', models.ForeignKey(blank=True, help_text='Source requisition this RFx was spawned from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_events', to='requisitions.requisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RfxTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rfx_type', models.CharField(choices=[('rfi', 'Request for Information (RFI)'), ('rfp', 'Request for Proposal (RFP)'), ('rfq', 'Request for Quotation (RFQ)')], default='rfi', max_length=10)),
                ('is_shared', models.BooleanField(default=True, help_text='Shared templates are visible to every user in the tenant.')),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_templates_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('tenant', 'title')},
            },
        ),
        migrations.CreateModel(
            name='RfxTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rfx.rfxtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfxTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('longtext', 'Long text / paragraph'), ('number', 'Number'), ('single_choice', 'Single choice (radio)'), ('multi_choice', 'Multiple choice (checkboxes)'), ('yes_no', 'Yes / No'), ('scale', 'Rating scale (0–max)'), ('date', 'Date'), ('file', 'File upload')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_scored', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rfx.rfxtemplatesection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfxSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rfx.rfxevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfxResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (vendor working)'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('rank', models.PositiveIntegerField(default=0, help_text='1 = highest; 0 = unranked')),
                ('notes', models.TextField(blank=True)),
                ('decision_reason', models.CharField(blank=True, help_text='Reason recorded when the response was shortlisted or rejected.', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfx.rfxevent')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_responses_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_responses', to='vendors.vendor')),
            ],
            options={
                'ordering': ['rank', '-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RfxQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Short text'), ('longtext', 'Long text / paragraph'), ('number', 'Number'), ('single_choice', 'Single choice (radio)'), ('multi_choice', 'Multiple choice (checkboxes)'), ('yes_no', 'Yes / No'), ('scale', 'Rating scale (0–max)'), ('date', 'Date'), ('file', 'File upload')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_scored', models.BooleanField(default=False, help_text='If true, evaluators score this answer and the weight contributes to the response score.')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight in percent (0–100). All scored question weights on an event must sum to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('max_score', models.PositiveIntegerField(default=5, help_text='Maximum evaluator score (default 5 for a 1–5 scale).')),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choice strings — required for single_choice / multi_choice; ignored otherwise.')),
                ('position', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rfx.rfxsection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RfxInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='invited', max_length=12)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='rfx.rfxevent')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_invitations', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='RfxEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('comment', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_evaluations', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rfx.rfxquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rfx.rfxresponse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='RfxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='rfx_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rfx.rfxevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfx_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RfxAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_choices', models.JSONField(blank=True, default=list, help_text='List of selected choice strings (one entry for single_choice).')),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='rfx_answers/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rfx.rfxquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rfx.rfxresponse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['question__section__position', 'question__position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='rfxresponse',
            index=models.Index(fields=['tenant', 'status'], name='rfx_rfxresp_tenant__f00d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='rfxresponse',
            index=models.Index(fields=['event', 'rank'], name='rfx_rfxresp_event_i_f951a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxresponse',
            unique_together={('event', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='rfxinvitee',
            index=models.Index(fields=['tenant', 'vendor', 'status'], name='rfx_rfxinvi_tenant__0d0e2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxinvitee',
            unique_together={('event', 'vendor')},
        ),
        migrations.AddIndex(
            model_name='rfxevent',
            index=models.Index(fields=['tenant', 'status'], name='rfx_rfxeven_tenant__590851_idx'),
        ),
        migrations.AddIndex(
            model_name='rfxevent',
            index=models.Index(fields=['tenant', 'rfx_type'], name='rfx_rfxeven_tenant__0d4f31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxevent',
            unique_together={('tenant', 'event_number')},
        ),
        migrations.AddIndex(
            model_name='rfxevaluation',
            index=models.Index(fields=['tenant', 'response'], name='rfx_rfxeval_tenant__0c42c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfxevaluation',
            unique_together={('response', 'question', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='rfxanswer',
            unique_together={('response', 'question')},
        ),
    ]
