# Generated by Django 4.2.28 on 2026-06-06 18:36

import apps.dms.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(help_text='Auto DOC-<SLUG>-NNNNN.', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('quote', 'Quote / Proposal'), ('spec', 'Specification'), ('warranty', 'Warranty / Guarantee'), ('contract', 'Contract / Legal'), ('policy', 'Procurement Policy'), ('sop', 'SOP / Procedure'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted')], default='internal', help_text='Access sensitivity — restricted documents are owner/manager only.', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for discovery / search.', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='dms_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'md', 'rtf', 'csv', 'xlsx']), apps.dms.validators.validate_upload_size])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes.')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True, help_text='The searchable extracted text.')),
                ('index_status', models.CharField(choices=[('pending', 'Pending extraction'), ('indexed', 'Indexed'), ('failed', 'Extraction failed'), ('unsupported', 'Unsupported type')], default='pending', max_length=12)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extraction_engine', models.CharField(blank=True, max_length=20)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dms.document')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_published', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(help_text='created / version_uploaded / version_published / status_changed / indexed.', max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(blank=True, max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dms.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dms.documentversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The published version end-users access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='dms.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_number', models.CharField(help_text='Auto TPL-<SLUG>-NNNNN.', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rfp', 'RFP / RFQ'), ('rfi', 'RFI'), ('evaluation', 'Bid Evaluation'), ('negotiation', 'Negotiation'), ('sop', 'SOP / Procedure'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('body', models.TextField(help_text='The reusable template content.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='dms_policyt_tenant__74d25a_idx'), models.Index(fields=['tenant', 'category'], name='dms_policyt_tenant__9304dc_idx')],
                'unique_together': {('tenant', 'template_number')},
            },
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['tenant', 'index_status'], name='dms_documen_tenant__9d0e95_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['tenant', 'status'], name='dms_documen_tenant__dd3c12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['tenant', 'document'], name='dms_documen_tenant__b624a3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='dms_documen_tenant__168143_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'category'], name='dms_documen_tenant__856862_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('tenant', 'document_number')},
        ),
    ]
