# Generated by Django 4.2.28 on 2026-06-06 12:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0002_vendor_performance_band_vendor_performance_score_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening_number', models.CharField(help_text='Auto SCR-<SLUG>-NNNNN.', max_length=40)),
                ('screened_name', models.CharField(help_text='The name actually screened.', max_length=200)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('status', models.CharField(choices=[('clear', 'Clear — no match'), ('review', 'Potential match — needs review'), ('blocked', 'Confirmed match — blocked')], default='clear', max_length=10)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('lists_checked', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField(blank=True, null=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_screenings', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, help_text='Screened vendor (blank = an ad-hoc name screen).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_screenings', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitored', models.BooleanField(default=True, help_text='Whether the cron refresh keeps this vendor up to date.')),
                ('credit_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Latest 0-100 credit-health score (higher = healthier).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('outlook', models.CharField(choices=[('positive', 'Positive'), ('stable', 'Stable'), ('negative', 'Negative')], default='stable', max_length=10)),
                ('exposure_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Open commitments + unpaid invoices at last refresh.', max_digits=14)),
                ('overdue_invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('provider', models.CharField(default='mock', max_length=40)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_risk_profile', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-exposure_amount', 'vendor_id'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_number', models.CharField(help_text='Auto FRD-<SLUG>-NNNNN.', max_length=40)),
                ('rule_code', models.CharField(blank=True, help_text='Snapshot of the rule code.', max_length=30)),
                ('rule_name', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('subject_type', models.CharField(blank=True, help_text='e.g. PurchaseOrder / SupplierInvoice / Vendor.', max_length=40)),
                ('subject_id', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Matched group / amounts / ids.')),
                ('signature', models.CharField(help_text='Stable dedupe key (rule + offending entity set).', max_length=120)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_assigned', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(help_text='Auto POL-<SLUG>-NNNNN.', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('procurement', 'Procurement'), ('ethics', 'Ethics & Conduct'), ('security', 'Security'), ('finance', 'Finance'), ('other', 'Other')], default='procurement', max_length=15)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('requires_acknowledgment', models.BooleanField(default=True, help_text='Whether users must sign off on the published version.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestrictedPartyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_name', models.CharField(help_text='e.g. OFAC-SDN, SAM-EPLS, EU-CFSP.', max_length=60)),
                ('entity_name', models.CharField(max_length=200)),
                ('entry_type', models.CharField(choices=[('person', 'Individual'), ('organization', 'Organization'), ('vessel', 'Vessel / Asset')], default='organization', max_length=12)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('program', models.CharField(blank=True, help_text='Sanctions program / reason.', max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Known aliases (a/k/a).')),
                ('source_ref', models.CharField(blank=True, help_text='List entry id / URL.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['entity_name'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_name', models.CharField(max_length=200)),
                ('list_name', models.CharField(blank=True, max_length=60)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fuzzy match confidence (0-100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matched_field', models.CharField(blank=True, help_text='name / alias.', max_length=40)),
                ('decision', models.CharField(choices=[('pending', 'Pending review'), ('false_positive', 'False positive'), ('confirmed', 'Confirmed match')], default='pending', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dispositioned_at', models.DateTimeField(blank=True, null=True)),
                ('dispositioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_dispositions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='compliance.restrictedpartyentry')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='compliance.compliancescreening')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compliance.policy')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_published', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='compliance.policyversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The published version users acknowledge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='compliance.policyversion'),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('split_po', 'Split purchase orders (threshold avoidance)'), ('duplicate_invoice', 'Duplicate invoice'), ('round_amount', 'Suspicious round-number amount'), ('vendor_bank_conflict', 'Shared vendor bank account'), ('conflict_of_interest', 'Vendor / employee conflict of interest')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=8)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Tuning, e.g. {"window_days": 14, "amount_floor": 5000}.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alert_events', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='compliance.fraudalert')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='compliance.fraudrule'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='FinancialRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('credit_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('outlook', models.CharField(choices=[('positive', 'Positive'), ('stable', 'Stable'), ('negative', 'Negative')], default='stable', max_length=10)),
                ('exposure_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('open_po_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='mock', max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='compliance.financialriskprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_risk_snapshots', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='restrictedpartyentry',
            index=models.Index(fields=['tenant', 'list_name'], name='compliance__tenant__1185ca_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictedpartyentry',
            index=models.Index(fields=['tenant', 'is_active'], name='compliance__tenant__4de357_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('policy', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['tenant', 'user'], name='compliance__tenant__784ff6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policyacknowledgment',
            unique_together={('tenant', 'policy_version', 'user')},
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'status'], name='compliance__tenant__7e8aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['tenant', 'category'], name='compliance__tenant__136570_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together={('tenant', 'policy_number')},
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['tenant', 'is_active'], name='compliance__tenant__9e1260_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fraudrule',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['tenant', 'status'], name='compliance__tenant__f829e0_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['tenant', 'severity'], name='compliance__tenant__a8f553_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['tenant', 'vendor'], name='compliance__tenant__6d949b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fraudalert',
            unique_together={('tenant', 'signature')},
        ),
        migrations.AddIndex(
            model_name='financialrisksnapshot',
            index=models.Index(fields=['tenant', 'vendor', 'as_of_date'], name='compliance__tenant__e2a863_idx'),
        ),
        migrations.AddIndex(
            model_name='financialriskprofile',
            index=models.Index(fields=['tenant', 'band'], name='compliance__tenant__3f697c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialriskprofile',
            index=models.Index(fields=['tenant', 'monitored'], name='compliance__tenant__348dad_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancescreening',
            index=models.Index(fields=['tenant', 'status'], name='compliance__tenant__2cba79_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancescreening',
            index=models.Index(fields=['tenant', 'vendor'], name='compliance__tenant__db9bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancescreening',
            unique_together={('tenant', 'screening_number')},
        ),
    ]
