# Generated by Django 4.2.28 on 2026-05-22 19:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickrequisition',
            name='number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='quickrequisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='quickrequisitionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='quickrequisition',
            unique_together={('tenant', 'number')},
        ),
    ]
