# Generated by Django 4.2.28 on 2026-06-08 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('frequency', models.CharField(choices=[('manual', 'Manual only'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('scope', models.CharField(choices=[('full', 'Full (database + media)'), ('db_only', 'Database only'), ('media_only', 'Media / files only')], default='full', max_length=12)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('storage_target', models.CharField(default='local', help_text='local / s3 / gcs / azure.', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('run_hour', models.PositiveSmallIntegerField(default=2, help_text='Hour of day (0–23) to run.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_number', models.CharField(help_text='Auto BKR-<SLUG>-NNNNN.', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('scope', models.CharField(choices=[('full', 'Full (database + media)'), ('db_only', 'Database only'), ('media_only', 'Media / files only')], default='full', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('connector', models.CharField(blank=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='sysadmin.backuppolicy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('protocol', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect'), ('ldap', 'LDAP / Active Directory')], default='saml', max_length=8)),
                ('connector', models.CharField(default='mock', help_text='Backend that performs the handshake (mock by default).', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='Primary provider offered on the login page.')),
                ('entity_id', models.CharField(blank=True, max_length=255, verbose_name='Entity ID / Issuer')),
                ('sso_url', models.URLField(blank=True, max_length=500, verbose_name='Sign-in URL')),
                ('slo_url', models.URLField(blank=True, max_length=500, verbose_name='Sign-out URL')),
                ('metadata_url', models.URLField(blank=True, max_length=500)),
                ('x509_cert', models.TextField(blank=True, verbose_name='Signing certificate (PEM)')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('server_uri', models.CharField(blank=True, help_text='ldaps://host:636', max_length=255)),
                ('bind_dn', models.CharField(blank=True, max_length=255)),
                ('bind_password', models.CharField(blank=True, max_length=255)),
                ('user_search_base', models.CharField(blank=True, max_length=255)),
                ('user_filter', models.CharField(blank=True, default='(sAMAccountName=%(user)s)', max_length=255)),
                ('attribute_mapping', models.JSONField(blank=True, default=dict, help_text='IdP attribute -> user field, e.g. {"email": "mail", "first_name": "givenName"}.')),
                ('jit_provisioning', models.BooleanField(default=True, help_text='Auto-create a user on first successful login.')),
                ('default_role_code', models.CharField(default='requester', help_text='Role assigned to JIT-provisioned users.', max_length=40)),
                ('allowed_domains', models.CharField(blank=True, help_text='Comma-separated email domains permitted to use this IdP.', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable identifier, e.g. "buyer".', max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in role (mirrors User.role) — cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('target_url', models.URLField(max_length=500)),
                ('events', models.JSONField(blank=True, default=list, help_text='Subscribed event codes.')),
                ('secret', models.CharField(blank=True, help_text='HMAC signing secret (masked).', max_length=255)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.CharField(blank=True, max_length=10)),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=3, default=0, help_text='Percent.', max_digits=6)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales', 'Sales Tax'), ('wht', 'Withholding Tax'), ('none', 'No Tax / Exempt')], default='vat', max_length=8)),
                ('jurisdiction', models.CharField(blank=True, max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_legal_name', models.CharField(blank=True, max_length=200)),
                ('base_currency_code', models.CharField(default='USD', max_length=3)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('date_format', models.CharField(choices=[('Y-m-d', '2026-12-31 (ISO)'), ('d/m/Y', '31/12/2026 (DMY)'), ('m/d/Y', '12/31/2026 (MDY)'), ('d M Y', '31 Dec 2026')], default='Y-m-d', max_length=20)),
                ('time_format', models.CharField(choices=[('H:i', '24-hour (14:30)'), ('h:i A', '12-hour (02:30 PM)')], default='H:i', max_length=20)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=30)),
                ('weekend_days', models.CharField(default='6,0', help_text='Comma-separated weekday numbers (Mon=0 … Sun=6).', max_length=20)),
                ('locale', models.CharField(default='en-us', max_length=10)),
                ('default_tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_configs', to='sysadmin.taxcode')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_configuration', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant_id'],
            },
        ),
        migrations.CreateModel(
            name='SSOLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject_id', models.CharField(blank=True, help_text='IdP subject / nameID.', max_length=255)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('provisioned', 'Provisioned (JIT)')], default='success', max_length=12)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to='sysadmin.identityprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(max_length=60)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sysadmin.roledefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['permission_code'],
            },
        ),
        migrations.CreateModel(
            name='RestoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('restored', 'Restored'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('backup_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_requests', to='sysadmin.backuprun')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_requests_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.SlugField(help_text='What it numbers, e.g. "purchase_order".', max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(blank=True, max_length=12)),
                ('suffix', models.CharField(blank=True, max_length=12)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('include_year', models.BooleanField(default=False)),
                ('reset_frequency', models.CharField(choices=[('never', 'Never (continuous)'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='never', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217, e.g. USD.', max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(blank=True, max_length=6)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=6, default=1, help_text='How many base-currency units one unit of this currency is worth.', max_digits=18)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key_prefix', models.CharField(help_text='Public, non-secret prefix shown in lists (e.g. pms_AB12CD).', max_length=24)),
                ('hashed_secret', models.CharField(help_text='SHA-256 of the secret. Never plaintext.', max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='List of permission codes.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('response_excerpt', models.CharField(blank=True, max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sysadmin.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'webhook', 'status'], name='sysadmin_we_tenant__7e0ec1_idx'), models.Index(fields=['tenant', 'status'], name='sysadmin_we_tenant__0ad303_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['tenant', 'is_active'], name='sysadmin_we_tenant__e37cb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taxcode',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='ssologinevent',
            index=models.Index(fields=['tenant', 'provider', 'outcome'], name='sysadmin_ss_tenant__1bb008_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['tenant', 'permission_code'], name='sysadmin_ro_tenant__444330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('tenant', 'role', 'permission_code')},
        ),
        migrations.AddIndex(
            model_name='roledefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='sysadmin_ro_tenant__ede6e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roledefinition',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='restorerequest',
            index=models.Index(fields=['tenant', 'status'], name='sysadmin_re_tenant__ea1091_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='numbersequence',
            unique_together={('tenant', 'doc_type')},
        ),
        migrations.AddIndex(
            model_name='identityprovider',
            index=models.Index(fields=['tenant', 'is_active'], name='sysadmin_id_tenant__6f2894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='identityprovider',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='backuprun',
            index=models.Index(fields=['tenant', 'status'], name='sysadmin_ba_tenant__262e66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backuprun',
            unique_together={('tenant', 'run_number')},
        ),
        migrations.AddIndex(
            model_name='backuppolicy',
            index=models.Index(fields=['tenant', 'is_active'], name='sysadmin_ba_tenant__dd2690_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backuppolicy',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['tenant', 'is_active'], name='sysadmin_ap_tenant__3ee5ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('tenant', 'key_prefix')},
        ),
    ]
