# Generated by Django 4.2.28 on 2026-06-06 11:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendor_performance_band_vendor_performance_score_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pip_number', models.CharField(help_text='Auto PIP-<SLUG>-NNNNN.', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Root cause / context.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Internal owner driving the plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Stable key, e.g. OTD / DEF / RESP.', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kpi_type', models.CharField(choices=[('on_time_delivery', 'On-Time Delivery'), ('defect_rate', 'Defect / Quality Rate'), ('responsiveness', 'Responsiveness'), ('price_variance', 'Price / Cost Variance'), ('feedback', '360° Feedback'), ('custom', 'Custom / Manual')], default='custom', max_length=20)),
                ('source', models.CharField(choices=[('auto', 'Auto-computed'), ('manual', 'Manual entry'), ('feedback', 'Feedback aggregate')], default='auto', max_length=10)),
                ('direction', models.CharField(choices=[('higher_better', 'Higher is better'), ('lower_better', 'Lower is better')], default='higher_better', max_length=13)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percent weight in the overall scorecard.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Goal raw value, e.g. 95 (% on-time) or 2 (% defects).', max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, help_text='%, days, count…', max_length=20)),
                ('green_threshold', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Normalised score at/above which the line is green.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amber_threshold', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Normalised score at/above which the line is amber.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scorecard_number', models.CharField(help_text='Auto SPC-<SLUG>-NNNNN.', max_length=40)),
                ('period_label', models.CharField(help_text='e.g. "Q1 2026".', max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating_band', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('acceptable', 'Acceptable'), ('poor', 'Poor'), ('critical', 'Critical')], default='acceptable', max_length=12)),
                ('is_current', models.BooleanField(default=False, help_text='The latest final scorecard for the vendor.')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards_generated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorecards', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_status_events', to=settings.AUTH_USER_MODEL)),
                ('improvement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='supplier_performance.improvementplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIPAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pip_actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('improvement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='supplier_performance.improvementplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='requested', max_length=12)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Overall 1 (poor) to 5 (excellent).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_feedback_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='The internal stakeholder reviewing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_feedback', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='scorecard',
            field=models.ForeignKey(blank=True, help_text='The scorecard that triggered the plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_plans', to='supplier_performance.scorecard'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='improvement_plans', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='ScorecardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_code', models.CharField(blank=True, max_length=40)),
                ('kpi_name', models.CharField(blank=True, max_length=120)),
                ('kpi_type', models.CharField(blank=True, max_length=20)),
                ('direction', models.CharField(blank=True, max_length=13)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, help_text='The measured metric (None = no source data in-period).', max_digits=14, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Normalised 0-100 (None = not scored).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight snapshot at generation.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='score * weight / 100 (display only).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_points', models.CharField(blank=True, help_text='Evidence, e.g. "138/150 receipts on time".', max_length=255)),
                ('is_manual', models.BooleanField(default=False)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecard_lines', to='supplier_performance.kpidefinition')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supplier_performance.scorecard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('scorecard', 'kpi')},
            },
        ),
        migrations.AddIndex(
            model_name='scorecard',
            index=models.Index(fields=['tenant', 'vendor', 'is_current'], name='supplier_pe_tenant__b13308_idx'),
        ),
        migrations.AddIndex(
            model_name='scorecard',
            index=models.Index(fields=['tenant', 'vendor', 'period_end'], name='supplier_pe_tenant__3c328e_idx'),
        ),
        migrations.AddIndex(
            model_name='scorecard',
            index=models.Index(fields=['tenant', 'status'], name='supplier_pe_tenant__dd7d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scorecard',
            unique_together={('tenant', 'scorecard_number')},
        ),
        migrations.AlterUniqueTogether(
            name='pipaction',
            unique_together={('improvement_plan', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='performancefeedback',
            index=models.Index(fields=['tenant', 'vendor', 'status'], name='supplier_pe_tenant__57e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='performancefeedback',
            index=models.Index(fields=['tenant', 'reviewer'], name='supplier_pe_tenant__766cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='kpidefinition',
            index=models.Index(fields=['tenant', 'is_active'], name='supplier_pe_tenant__f7dbee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpidefinition',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='improvementplan',
            index=models.Index(fields=['tenant', 'status'], name='supplier_pe_tenant__65d804_idx'),
        ),
        migrations.AddIndex(
            model_name='improvementplan',
            index=models.Index(fields=['tenant', 'vendor'], name='supplier_pe_tenant__8eb5c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='improvementplan',
            unique_together={('tenant', 'pip_number')},
        ),
    ]
