# Generated by Django 4.2.28 on 2026-06-06 18:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('catalog', '0001_initial'),
        ('goods_receipt', '0002_goodsreceiptline_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Auto CC-<SLUG>-NNNNN.', max_length=40)),
                ('scope', models.CharField(choices=[('full', 'Full warehouse'), ('location', 'By location'), ('abc', 'By ABC class')], default='full', max_length=12)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'Counting'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_counted', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_posted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('system_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='On-hand snapshot when the count was created.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Physically counted quantity (blank = not yet counted).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='counted − system at post time (signed).', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('counted', models.BooleanField(default=False)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.cyclecount')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Auto GI-<SLUG>-NNNNN.', max_length=40)),
                ('issue_type', models.CharField(choices=[('consumption', 'Internal consumption'), ('return_to_stock', 'Return to stock'), ('write_off', 'Write-off / scrap')], default='consumption', max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('cost_center', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issues_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issues_issued', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issues_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsissue')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, help_text='Denormalised from the catalog item (GRN join key).', max_length=60)),
                ('is_stocked', models.BooleanField(default=True, help_text='Whether this item is tracked + eligible for reorder automation.')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reorder when available stock falls to/below this level.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity the auto-requisition orders.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('safety_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Buffer kept above zero (informational).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('abc_class', models.CharField(blank=True, choices=[('A', 'A — high value'), ('B', 'B — medium'), ('C', 'C — low value')], max_length=1)),
                ('moving_avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Weighted-average unit cost, recomputed on each receipt.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalised sum of all stock-level buckets.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Soft-allocated quantity (not available to issue).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_reordered_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(help_text='The catalog master this stock tracks.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_item', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. WH-MAIN.', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='The fallback warehouse when a receipt has no mapped bin.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Bin code, e.g. A-01-03.', max_length=40)),
                ('aisle', models.CharField(blank=True, max_length=20)),
                ('rack', models.CharField(blank=True, max_length=20)),
                ('shelf', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Auto MOV-<SLUG>-NNNNN.', max_length=40)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt (from GRN)'), ('issue', 'Goods issue'), ('return', 'Return to stock'), ('adjustment', 'Manual adjustment'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('count_adjustment', 'Cycle-count adjustment')], max_length=20)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Signed change (+ in / - out).', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Item on-hand after this movement (audit nicety).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('cycle_count_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.cyclecountline')),
                ('goods_issue_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.goodsissueline')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.warehouselocation')),
                ('source_goods_receipt_line', models.OneToOneField(blank=True, help_text='The GRN line this receipt was synced from (idempotency watermark).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movement', to='goods_receipt.goodsreceiptline')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('to_location', models.ForeignKey(blank=True, help_text='Destination bin for a transfer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='inventory.warehouselocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('batch_number', models.CharField(blank=True, max_length=80)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('available', 'Available'), ('quarantine', 'Quarantine'), ('damaged', 'Damaged')], default='available', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expiry_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_levels', to='inventory.warehouselocation')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='inventory.stockitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['stock_item_id', 'location_id'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_items', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_items', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reorder_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requisitions.requisition'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='GoodsIssueStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issue_events', to=settings.AUTH_USER_MODEL)),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.goodsissue')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='goodsissueline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_issue_lines', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='goodsissueline',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issue_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='goodsissueline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_issues', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='CycleCountStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_events', to=settings.AUTH_USER_MODEL)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.cyclecount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_w_tenant__1ffae9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('tenant', 'warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_w_tenant__76c9ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'stock_item', 'created_at'], name='inventory_s_tenant__77a256_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'movement_type'], name='inventory_s_tenant__2cbf2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockmovement',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['tenant', 'stock_item'], name='inventory_s_tenant__1bee2a_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_s_tenant__398099_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['tenant', 'expiry_date'], name='inventory_s_tenant__98682c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('tenant', 'stock_item', 'location', 'lot_number', 'batch_number', 'serial_number', 'expiry_date', 'condition')},
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'sku'], name='inventory_s_tenant__e16b97_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tenant', 'is_stocked'], name='inventory_s_tenant__f0dd47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('tenant', 'catalog_item')},
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['tenant', 'status'], name='inventory_g_tenant__fb6adc_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsissue',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_g_tenant__d4e98a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsissue',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='cyclecount',
            index=models.Index(fields=['tenant', 'status'], name='inventory_c_tenant__869ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='cyclecount',
            index=models.Index(fields=['tenant', 'warehouse'], name='inventory_c_tenant__7ff799_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cyclecount',
            unique_together={('tenant', 'number')},
        ),
    ]
