# Generated by Django 4.2.28 on 2026-06-05 20:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='price_tolerance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price tolerance % for three-way match. Blank = use the tenant default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='qty_tolerance_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity tolerance % for three-way match. Blank = use the tenant default.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
