# Generated by Django 4.2.28 on 2026-06-05 19:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('requisitions', '0001_initial'),
        ('core', '0001_initial'),
        ('goods_receipt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('net_days', models.PositiveIntegerField(default=30, help_text='Days from the invoice date until payment is due.')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Early-payment discount percentage (0 = none).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_days', models.PositiveIntegerField(default=0, help_text='Pay within this many days to take the discount.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The amount to disburse (net of any discount taken).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('take_discount', models.BooleanField(default=False)),
                ('discount_taken', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=16)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Cheque no. / remittance reference.', max_length=120)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('gateway_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Internal control number (SINV-<SLUG>-NNNNN).', max_length=40)),
                ('supplier_invoice_ref', models.CharField(blank=True, help_text="The supplier's own invoice number.", max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('match_status', models.CharField(choices=[('unmatched', 'Not matched'), ('matched', 'Matched'), ('exceptions', 'Exceptions')], default='unmatched', max_length=12)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, help_text='Date the invoice arrived / was captured.', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('discount_due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Early-payment discount available on this invoice (per the payment term).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source_file', models.FileField(blank=True, null=True, upload_to='invoice_docs/')),
                ('ocr_engine', models.CharField(blank=True, max_length=40)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='OCR extraction confidence (0-100); blank for manual entry.', max_digits=5, null=True)),
                ('ocr_raw', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('submitted_via_portal', models.BooleanField(default=False, help_text='True if the supplier submitted this through the portal.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('match_override', models.BooleanField(default=False, help_text='True if approved despite three-way-match exceptions.')),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('overdue_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('discount_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('disputed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_disputed', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='goods_receipt.goodsreceipt')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='invoicing.paymentterm')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='The PO this invoice bills against (for three-way matching).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='purchase_orders.purchaseorder')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_status_events', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='invoicing.supplierinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucherStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher_status_events', to=settings.AUTH_USER_MODEL)),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='invoicing.paymentvoucher')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='supplier_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='invoicing.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='vendor',
            field=models.ForeignKey(help_text='The supplier being paid (denormalised from the invoice).', on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='vendors.vendor'),
        ),
        migrations.CreateModel(
            name='InvoiceDisputeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_from_vendor', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_dispute_notes', to=settings.AUTH_USER_MODEL)),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_notes', to='invoicing.supplierinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(default='unit', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('match_status', models.CharField(choices=[('pending', 'Not matched'), ('matched', 'Matched'), ('qty_variance', 'Quantity variance'), ('price_variance', 'Price variance'), ('over_billed', 'Over-billed'), ('no_receipt', 'Not yet received'), ('no_po', 'No PO line')], default='pending', max_length=14)),
                ('matched_po_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ordered qty on the matched PO line.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('matched_received_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Qty received & accepted against the PO line (via the GRN or the fulfilment delivery confirmation — both post only accepted qty).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('qty_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoiced qty − received (accepted) qty.', max_digits=14)),
                ('price_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Invoiced unit price − PO unit price.', max_digits=14)),
                ('match_note', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_lines', to='requisitions.accountcode')),
                ('goods_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoice_lines', to='goods_receipt.goodsreceiptline')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='purchase_orders.purchaseorderline')),
                ('supplier_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.supplierinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'unique_together': {('supplier_invoice', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'status'], name='invoicing_s_tenant__3c16b3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'match_status'], name='invoicing_s_tenant__b53b94_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'vendor'], name='invoicing_s_tenant__ca1a21_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'purchase_order'], name='invoicing_s_tenant__7c45f5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'due_date'], name='invoicing_s_tenant__50e52e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['tenant', 'status'], name='invoicing_p_tenant__7c4183_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['tenant', 'vendor'], name='invoicing_p_tenant__369a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['tenant', 'scheduled_date'], name='invoicing_p_tenant__4797b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentvoucher',
            unique_together={('tenant', 'voucher_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentterm',
            unique_together={('tenant', 'code')},
        ),
    ]
