# Generated by Django 4.2.28 on 2026-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='currency_mismatch',
            field=models.BooleanField(default=False, help_text="True if the invoice currency differs from its PO's currency."),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='dispute_sla_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['tenant', 'status', 'disputed_at'], name='invoicing_s_tenant__659fa2_idx'),
        ),
    ]
