# Generated by Django 4.2.28 on 2026-06-04 17:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('fulfillment', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grn_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('under_inspection', 'Under inspection'), ('inspected', 'Inspected'), ('posted', 'Posted'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_note_ref', models.CharField(blank=True, max_length=80)),
                ('warehouse_location', models.CharField(blank=True, max_length=120)),
                ('carrier_note', models.CharField(blank=True, max_length=255)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial')], max_length=10)),
                ('inspection_note', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('inspection_alerted_at', models.DateTimeField(blank=True, help_text='Set when the overdue-inspection alert was raised.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_inspected', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_posted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='The purchase order these goods were received against.', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchase_orders.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, help_text='The shipment/ASN this receipt was booked from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='fulfillment.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(help_text='The supplier (denormalised from the PO for filtering).', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(default='unit', max_length=30)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity physically received on this GRN.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accepted_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity that passed inspection.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity that failed inspection (-> RTV).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('posted_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accepted qty already posted to the PO line — the idempotency watermark so re-posting a GRN never double-counts.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discrepancy_type', models.CharField(choices=[('none', 'None'), ('short', 'Short / under-delivered'), ('over', 'Over-delivered'), ('damaged', 'Damaged'), ('wrong_item', 'Wrong item'), ('quality', 'Quality failure')], default='none', max_length=12)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('line_status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('inspected', 'Inspected'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partially accepted')], default='pending', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='goods_receipt.goodsreceipt')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='purchase_orders.purchaseorderline')),
                ('shipment_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='fulfillment.shipmentline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnToVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rtv_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('authorized', 'Authorized'), ('shipped', 'Shipped'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('rma_number', models.CharField(blank=True, help_text='Supplier return-merchandise authorisation #.', max_length=80)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_note', models.CharField(blank=True, max_length=255)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtvs_authorized', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtvs_created', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='goods_receipt.goodsreceipt')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_to_vendor', to='purchase_orders.purchaseorder')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtvs_shipped', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_to_vendor', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('uom', models.CharField(default='unit', max_length=30)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_tags', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='goods_receipt.goodsreceipt')),
                ('goods_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='goods_receipt.goodsreceiptline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_status_events', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='goods_receipt.goodsreceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion', models.CharField(choices=[('packaging_intact', 'Packaging intact'), ('quantity_matches', 'Quantity matches documents'), ('no_damage', 'No visible damage'), ('labelling_correct', 'Labelling correct'), ('documentation_present', 'Documentation present')], max_length=40)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='pass', max_length=4)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_checks', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='goods_receipt.goodsreceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnToVendorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(default='unit', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('goods_receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rtv_lines', to='goods_receipt.goodsreceiptline')),
                ('rtv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='goods_receipt.returntovendor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'unique_together': {('rtv', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'status'], name='goods_recei_tenant__d00893_idx'),
        ),
        migrations.AddIndex(
            model_name='returntovendor',
            index=models.Index(fields=['tenant', 'vendor'], name='goods_recei_tenant__2521dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returntovendor',
            unique_together={('tenant', 'rtv_number')},
        ),
        migrations.AddIndex(
            model_name='receipttag',
            index=models.Index(fields=['tenant', 'goods_receipt'], name='goods_recei_tenant__3d23d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receipttag',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptline',
            unique_together={('goods_receipt', 'line_no')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptcheck',
            unique_together={('goods_receipt', 'criterion')},
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'status'], name='goods_recei_tenant__0e34bb_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'vendor'], name='goods_recei_tenant__013947_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'purchase_order'], name='goods_recei_tenant__ab96dc_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant', 'received_date'], name='goods_recei_tenant__acb933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceipt',
            unique_together={('tenant', 'grn_number')},
        ),
    ]
