# Generated by Django 4.2.28 on 2026-06-05 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('goods_receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='bin_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='lot_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='receipttag',
            name='bin_location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='receipttag',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipttag',
            name='lot_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='GoodsReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], default='photo', max_length=10)),
                ('file', models.FileField(upload_to='goods_receipt/attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='goods_receipt.goodsreceipt')),
                ('goods_receipt_line', models.ForeignKey(blank=True, help_text='Optional — the received line this evidence documents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='goods_receipt.goodsreceiptline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'goods_receipt'], name='goods_recei_tenant__4dd6a9_idx')],
            },
        ),
    ]
