# Generated by Django 4.2.28 on 2026-06-03 20:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('advised', 'Advised (ASN sent)'), ('in_transit', 'In transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('received', 'Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], default='draft', max_length=20)),
                ('packing_slip_number', models.CharField(blank=True, max_length=80)),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('total_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('weight_uom', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=3)),
                ('packing_note', models.TextField(blank=True)),
                ('advised_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('carrier_code', models.CharField(blank=True, help_text='Carrier connector key (e.g. "mock") used for live tracking sync.', max_length=40)),
                ('service_level', models.CharField(blank=True, max_length=80)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('freight_status', models.CharField(blank=True, help_text='Last carrier status label.', max_length=60)),
                ('tracking_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('received_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('partial', 'Partial / short'), ('rejected', 'Rejected')], max_length=10)),
                ('delivery_note', models.CharField(blank=True, max_length=255)),
                ('proof_reference', models.CharField(blank=True, help_text='Proof-of-delivery reference (signature / photo id).', max_length=120)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery_alerted_at', models.DateTimeField(blank=True, help_text='Set when the overdue-delivery alert was raised.', null=True)),
                ('advised_by', models.ForeignKey(blank=True, help_text='Supplier portal user (or buyer recording on their behalf).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_advised', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(help_text='The purchase order this shipment fulfils.', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='purchase_orders.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(help_text='The shipping supplier (denormalised from the PO for filtering).', on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_status_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='fulfillment.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('packing_slip', 'Packing slip'), ('bol', 'Bill of lading'), ('pod', 'Proof of delivery'), ('other', 'Other')], default='other', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='shipment_docs/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fulfillment.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Backorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('promised', 'Promised'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders_created', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_backorders', to='fulfillment.shipment')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='purchase_orders.purchaseorder')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorders', to='purchase_orders.purchaseorderline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['expected_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('occurred_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('carrier', 'Carrier API'), ('webhook', 'Carrier webhook')], default='manual', max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_tracking_events', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='fulfillment.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'shipment'], name='fulfillment_tenant__bf5ce1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(default='unit', max_length=30)),
                ('shipped_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity confirmed received on this shipment.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('posted_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='How much has already been posted to the PO line — the idempotency watermark so re-confirming a delivery never double-counts.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('backordered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carton_reference', models.CharField(blank=True, max_length=80)),
                ('package_no', models.CharField(blank=True, max_length=40)),
                ('line_status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('received', 'Received'), ('short', 'Short / backordered')], default='pending', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='purchase_orders.purchaseorderline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fulfillment.shipment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['line_no', 'id'],
                'unique_together': {('shipment', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'status'], name='fulfillment_tenant__1af945_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'vendor'], name='fulfillment_tenant__081985_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'purchase_order'], name='fulfillment_tenant__a0faa7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'estimated_delivery_date'], name='fulfillment_tenant__acea56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together={('tenant', 'shipment_number')},
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['tenant', 'status'], name='fulfillment_tenant__567ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['tenant', 'purchase_order'], name='fulfillment_tenant__e0b46a_idx'),
        ),
    ]
