# Generated by Django 4.2.28 on 2026-06-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shipmentline',
            unique_together={('shipment', 'line_no'), ('shipment', 'purchase_order_line')},
        ),
    ]
