# Generated by Django 4.2.28 on 2026-06-06 11:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='performance_band',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('acceptable', 'Acceptable'), ('poor', 'Poor'), ('critical', 'Critical')], default='acceptable', max_length=12),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalised from the latest current Scorecard (0-100).', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['tenant', 'performance_band'], name='vendors_ven_tenant__f9f39e_idx'),
        ),
    ]
