# Generated by Django 4.2.28 on 2026-06-02 21:02

import apps.catalog.validators
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('requisitions', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.catalogcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'Catalog categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_number', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=80)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated search terms.', max_length=255)),
                ('source', models.CharField(choices=[('internal', 'Internal stock item'), ('supplier', 'Supplier product')], default='internal', max_length=10)),
                ('uom', models.CharField(choices=[('each', 'Each'), ('box', 'Box'), ('case', 'Case'), ('pack', 'Pack'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Litre'), ('m', 'Metre'), ('hour', 'Hour'), ('day', 'Day'), ('unit', 'Unit'), ('set', 'Set'), ('roll', 'Roll')], default='each', max_length=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='List unit price. The effective price is resolved from the tiers.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_order_qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog_items/')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('retired', 'Retired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.ForeignKey(blank=True, help_text='Default GL coding for this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='requisitions.accountcode')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.catalogcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPunchoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('protocol', models.CharField(choices=[('cxml', 'cXML'), ('oci', 'OCI (Open Catalog Interface)')], default='cxml', max_length=8)),
                ('setup_url', models.URLField(help_text='The supplier endpoint the PunchOutSetupRequest / OCI hook is sent to.', max_length=500)),
                ('from_identity', models.CharField(blank=True, max_length=120)),
                ('to_identity', models.CharField(blank=True, max_length=120)),
                ('sender_identity', models.CharField(blank=True, max_length=120)),
                ('shared_secret', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('extra_params', models.JSONField(blank=True, default=dict, help_text='Static OCI form fields (HOOK_URL is added at runtime).')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchout_configs', to='vendors.vendor')),
            ],
            options={
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='catalog_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx']), apps.catalog.validators.validate_upload_size])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('imported', 'Imported'), ('partially_imported', 'Partially imported'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of {row, field, message}.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='catalog.catalogcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_uploads', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_uploads', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PunchoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_cookie', models.CharField(max_length=64, unique=True)),
                ('return_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('redirected', 'Redirected'), ('returned', 'Returned'), ('expired', 'Expired'), ('failed', 'Failed')], default='initiated', max_length=12)),
                ('start_page_url', models.URLField(blank=True, max_length=1000)),
                ('cart_data', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redirected_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.supplierpunchoutconfig')),
                ('requisition', models.ForeignKey(blank=True, help_text='Optional cart destination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punchout_sessions', to='requisitions.requisition')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punchout_sessions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchout_sessions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier_type', models.CharField(choices=[('volume', 'Volume break'), ('contract', 'Contract price')], default='volume', max_length=12)),
                ('min_quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Contract this negotiated price comes from (contract tiers only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_price_tiers', to='contracts.contract')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.catalogitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['item', '-tier_type', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPriceChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(max_length=48)),
                ('change_type', models.CharField(choices=[('base', 'Base price'), ('tiers', 'Tier schedule'), ('both', 'Base price & tiers')], default='base', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('new_base_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('proposed_tiers', models.JSONField(blank=True, default=list, help_text='List of {min_quantity, unit_price, tier_type, effective_from, effective_to} applied atomically on approval.')),
                ('prev_base_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('prev_tiers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_price_changes_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_price_changes_decided', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_change_requests', to='catalog.catalogitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_status_events', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='catalog.catalogitem')),
                ('price_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='catalog.catalogpricechangerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_items', to='catalog.punchoutsession'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='source_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_items', to='catalog.suppliercatalogupload'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Supplier counterparty (required when the source is a supplier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='supplierpunchoutconfig',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_sup_tenant__dbe022_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpunchoutconfig',
            unique_together={('tenant', 'vendor', 'name')},
        ),
        migrations.AddIndex(
            model_name='suppliercatalogupload',
            index=models.Index(fields=['tenant', 'status'], name='catalog_sup_tenant__4893ae_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercatalogupload',
            index=models.Index(fields=['tenant', 'vendor'], name='catalog_sup_tenant__1e8e74_idx'),
        ),
        migrations.AddIndex(
            model_name='punchoutsession',
            index=models.Index(fields=['tenant', 'status'], name='catalog_pun_tenant__019e39_idx'),
        ),
        migrations.AddIndex(
            model_name='punchoutsession',
            index=models.Index(fields=['tenant', 'vendor'], name='catalog_pun_tenant__1d2801_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogpricetier',
            index=models.Index(fields=['tenant', 'item', 'effective_from'], name='catalog_cat_tenant__c956e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogpricechangerequest',
            unique_together={('item', 'request_number')},
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'status'], name='catalog_cat_tenant__6001a1_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'source'], name='catalog_cat_tenant__7ef5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'category'], name='catalog_cat_tenant__07a07e_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['tenant', 'vendor'], name='catalog_cat_tenant__5857fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogitem',
            unique_together={('tenant', 'item_number')},
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['tenant', 'is_active'], name='catalog_cat_tenant__3f928c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogcategory',
            unique_together={('tenant', 'code')},
        ),
    ]
