# Generated by Django 4.2.28 on 2026-06-06 10:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_number', models.CharField(help_text='Auto BUD-<SLUG>-NNNNN.', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Denormalised sum of the allocation lines.', max_digits=14)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('over_budget_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Budget holder alerted on over-budget activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('account_code', models.ForeignKey(help_text='Cost centre / GL account this budget envelope governs.', on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='requisitions.accountcode')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.budget')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor_category', models.ForeignKey(blank=True, help_text='Optional: narrow the envelope to one commodity category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_allocations', to='vendors.vendorcategory')),
            ],
            options={
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_status_events', to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='budget.budget')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "FY2026" or "Q1 2026".', max_length=120)),
                ('period_type', models.CharField(choices=[('annual', 'Annual / Fiscal year'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('custom', 'Custom range')], default='annual', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('locked', 'Locked'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='The period new budgets default to.')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('available_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance at check time (0 when unbudgeted).', max_digits=14)),
                ('result', models.CharField(choices=[('pass', 'Within budget'), ('warn', 'Over budget (warned)'), ('block', 'Over budget (blocked)')], default='pass', max_length=6)),
                ('enforcement_mode', models.CharField(blank=True, max_length=6)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_checks', to='requisitions.accountcode')),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='budget.budgetallocation')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='budget.budget')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_checks', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_checks', to='requisitions.requisition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget.budgetperiod'),
        ),
        migrations.AddField(
            model_name='budget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='budgetperiod',
            index=models.Index(fields=['tenant', 'status'], name='budget_budg_tenant__d0d629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetperiod',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='budgetcheck',
            index=models.Index(fields=['tenant', 'result'], name='budget_budg_tenant__0fdad3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcheck',
            index=models.Index(fields=['tenant', 'requisition'], name='budget_budg_tenant__dbe587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('budget', 'account_code', 'vendor_category')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'status'], name='budget_budg_tenant__6c398f_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'period'], name='budget_budg_tenant__759ea1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('tenant', 'budget_number')},
        ),
    ]
