# Generated by Django 4.2.28 on 2026-06-05 20:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('dimension', models.CharField(choices=[('vendor', 'Vendor'), ('vendor_category', 'Category'), ('account_code', 'Cost Center / Account Code'), ('vendor_segment', 'Vendor Segment'), ('month', 'Month'), ('source_type', 'Source Type')], default='vendor_category', max_length=20)),
                ('measure', models.CharField(choices=[('amount_sum', 'Total spend'), ('net_sum', 'Net spend'), ('record_count', 'Record count'), ('amount_avg', 'Average spend')], default='amount_sum', max_length=20)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('doughnut', 'Doughnut'), ('line', 'Line')], default='bar', max_length=10)),
                ('basis', models.CharField(choices=[('actual', 'Actual (invoiced)'), ('committed', 'Committed (PO)')], default='actual', max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('invoice_line', 'Invoice line'), ('po_line', 'PO line')], help_text='Blank = both invoice and PO lines (within the chosen basis).', max_length=12)),
                ('maverick_only', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False, help_text='Shared reports are visible to every viewer in the tenant.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='requisitions.accountcode')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='vendors.vendor')),
                ('vendor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='vendors.vendorcategory')),
                ('vendor_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='vendors.vendorsegment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'owner'], name='spend_analy_tenant__9ebc82_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('invoice_line', 'Invoice line'), ('po_line', 'PO line')], max_length=12)),
                ('source_id', models.PositiveBigIntegerField()),
                ('basis', models.CharField(choices=[('actual', 'Actual (invoiced)'), ('committed', 'Committed (PO)')], max_length=10)),
                ('spend_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line total (pre-tax).', max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line tax (PO lines carry none).', max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net (pre-tax) spend; an explicit column for the "net" measure.', max_digits=14)),
                ('off_preferred_supplier', models.BooleanField(default=False)),
                ('off_contract', models.BooleanField(default=False)),
                ('off_po', models.BooleanField(default=False)),
                ('is_maverick', models.BooleanField(default=False)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_status', models.CharField(blank=True, max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('account_code', models.ForeignKey(blank=True, help_text='Cost centre / GL account (the "department" dimension).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_records', to='requisitions.accountcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_records', to='vendors.vendor')),
                ('vendor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_records', to='vendors.vendorcategory')),
                ('vendor_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_records', to='vendors.vendorsegment')),
            ],
            options={
                'ordering': ['-spend_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'spend_date'], name='spend_analy_tenant__f1e026_idx'), models.Index(fields=['tenant', 'vendor'], name='spend_analy_tenant__5a2d67_idx'), models.Index(fields=['tenant', 'source_type'], name='spend_analy_tenant__d7153b_idx'), models.Index(fields=['tenant', 'is_maverick'], name='spend_analy_tenant__4ca1ba_idx'), models.Index(fields=['tenant', 'basis'], name='spend_analy_tenant__81b3f3_idx'), models.Index(fields=['tenant', 'vendor_category'], name='spend_analy_tenant__3afa20_idx')],
                'unique_together': {('tenant', 'source_type', 'source_id')},
            },
        ),
    ]
